version: '3'

services:
  mysql:
      platform: "linux/x86_64"
      image: "mysql:8.0.28"
      restart: "always"
      volumes:
        - "./data/mysql:/var/lib/mysql"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: 11223344
      networks:
        - local-keycloak
  keycloak:
      platform: "linux/x86_64"
      image: "quay.io/keycloak/keycloak:17.0.0"
      hostname: "sso.local.com" #Set hostname of container
      restart: "always"
      command: "start-dev"
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: 11223344
        PROXY_ADDRESS_FORWARDING: "true"  #Enable proxy forward
        KC_DB: mysql
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: 11223344
        KC_DB_URL: "jdbc:mysql://mysql:3306/keycloak"
        KC_HTTP_RELATIVE_PATH: "/auth"  #Set realtive path to use when login
        KC_HOSTNAME: "sso.local.com" #Set hostname
        KC_PROXY: "passthrough" #Set proxy mode
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      ports:
        - "33333:8080"
      depends_on:
        - mysql
      networks:
        - local-keycloak

networks:
  local-keycloak: